//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefactorThis.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaymentMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefactorThis.Domain.Resources.PaymentMessages", typeof(PaymentMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to final partial payment received, invoice is now fully paid.
        /// </summary>
        internal static string FINAL_PARTIAL_FULLY_PAID {
            get {
                return ResourceManager.GetString("FINAL_PARTIAL_FULLY_PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoice was already fully paid.
        /// </summary>
        internal static string INVOICE_ALREADY_FULLY_PAID {
            get {
                return ResourceManager.GetString("INVOICE_ALREADY_FULLY_PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invoice is in an invalid state, it has an amount of 0 and it has payments..
        /// </summary>
        internal static string INVOICE_IS_INVALID {
            get {
                return ResourceManager.GetString("INVOICE_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoice is now fully paid.
        /// </summary>
        internal static string INVOICE_NOW_FULLY_PAID {
            get {
                return ResourceManager.GetString("INVOICE_NOW_FULLY_PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoice is now partially paid.
        /// </summary>
        internal static string INVOICE_NOW_PARTIALLY_PAID {
            get {
                return ResourceManager.GetString("INVOICE_NOW_PARTIALLY_PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no invoice matching this payment.
        /// </summary>
        internal static string NO_INVOICE_FOUND {
            get {
                return ResourceManager.GetString("NO_INVOICE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no payment needed.
        /// </summary>
        internal static string NO_PAYMENT_NEEDED {
            get {
                return ResourceManager.GetString("NO_PAYMENT_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to another partial payment received, still not fully paid.
        /// </summary>
        internal static string PARTIAL_PAYMENT_RECEIVED {
            get {
                return ResourceManager.GetString("PARTIAL_PAYMENT_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the payment is greater than the invoice amount.
        /// </summary>
        internal static string PAYMENT_GREATER_THAN_INVOICE {
            get {
                return ResourceManager.GetString("PAYMENT_GREATER_THAN_INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the payment is greater than the partial amount remaining.
        /// </summary>
        internal static string PAYMENT_GREATER_THAN_PARTIAL {
            get {
                return ResourceManager.GetString("PAYMENT_GREATER_THAN_PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment is not valid..
        /// </summary>
        internal static string PAYMENT_IS_NULL {
            get {
                return ResourceManager.GetString("PAYMENT_IS_NULL", resourceCulture);
            }
        }
    }
}
