//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefactorThis.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefactorThis.Domain.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another partial payment received, still not fully paid..
        /// </summary>
        internal static string AnotherPaymentReceived {
            get {
                return ResourceManager.GetString("AnotherPaymentReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final partial payment received, invoice is now fully paid..
        /// </summary>
        internal static string FinalPaymentReceived {
            get {
                return ResourceManager.GetString("FinalPaymentReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invoice is in an invalid state, it has an amount of 0 and it has payments..
        /// </summary>
        internal static string InvalidInvoice {
            get {
                return ResourceManager.GetString("InvalidInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice was already fully paid..
        /// </summary>
        internal static string InvoiceAlreadyPaid {
            get {
                return ResourceManager.GetString("InvoiceAlreadyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice is now fully paid..
        /// </summary>
        internal static string InvoiceFullyPaid {
            get {
                return ResourceManager.GetString("InvoiceFullyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice is now partially paid..
        /// </summary>
        internal static string InvoicePartiallyPaid {
            get {
                return ResourceManager.GetString("InvoicePartiallyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no invoice matching this payment..
        /// </summary>
        internal static string NoInvoice {
            get {
                return ResourceManager.GetString("NoInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payment needed..
        /// </summary>
        internal static string NoPaymentRequired {
            get {
                return ResourceManager.GetString("NoPaymentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment is greater than the invoice amount..
        /// </summary>
        internal static string PaymentGreaterThanAmount {
            get {
                return ResourceManager.GetString("PaymentGreaterThanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment is greater than the partial amount remaining..
        /// </summary>
        internal static string PaymentGreaterThanPartialRemaining {
            get {
                return ResourceManager.GetString("PaymentGreaterThanPartialRemaining", resourceCulture);
            }
        }
    }
}
